

## 'align_cmd_to_dots' --------------------------------------------------------

test_that("'align_cmd_to_dots' works on typical inputs supplied by makefile", {
    args_cmd <- list("file1", "file2", n_iter = 100, variant = "low")
    args_dots <- list(f1 = "f1", f2 = "f2", variant = "med", n_iter = 10)
    ans_obtained <- align_cmd_to_dots(args_cmd = args_cmd,
                                      args_dots = args_dots)
    ans_expected <- list(f1 = "file1", f2 = "file2", variant = "low", n_iter = 100)
    expect_identical(ans_obtained, ans_expected)
})

test_that("'align_cmd_to_dots' works when named argument comes before unnamed", {
    args_cmd <- list("file1", variant = "low", "file2", n_iter = 100)
    args_dots <- list(f1 = "f1", f2 = "f2", variant = "med", n_iter = 10)
    ans_obtained <- align_cmd_to_dots(args_cmd = args_cmd,
                                      args_dots = args_dots)
    ans_expected <- list(f1 = "file1", f2 = "file2", variant = "low", n_iter = 100)
    expect_identical(ans_obtained, ans_expected)
})

test_that("'align_cmd_to_dots' works when single unnamed argument", {
    args_cmd <- list("file1")
    args_dots <- list(f1 = "f1")
    ans_obtained <- align_cmd_to_dots(args_cmd = args_cmd,
                                      args_dots = args_dots)
    ans_expected <- list(f1 = "file1")
    expect_identical(ans_obtained, ans_expected)
})

test_that("'align_cmd_to_dots' works 'args_cmd' and 'args_dots' both length 0", {
    args_cmd <- list()
    args_dots <- list()
    ans_obtained <- align_cmd_to_dots(args_cmd = args_cmd,
                                      args_dots = args_dots)
    ans_expected <- list()
    expect_identical(ans_obtained, ans_expected)
})


## 'assign_args' --------------------------------------------------------------

test_that("'assign_args' creates correct objects in the parent frame, and returns as list", {
    args <- list(xx = 1, yy = "hello", zz = TRUE)
    envir <- new.env()
    ans_obtained <- assign_args(args, envir = envir)
    expect_identical(envir$xx, 1)
    expect_identical(envir$yy, "hello")
    expect_identical(envir$zz, TRUE)
    expect_identical(ans_obtained, args)
})

test_that("'assign_args' works with empty args", {
    args <- list()
    envir <- new.env()
    ans_obtained <- assign_args(args, envir = envir)
    expect_identical(length(envir), 0L)
    expect_identical(ans_obtained, args)
})
    

## 'check_args_cmd' ----------------------------------------------------------

test_that("'check_args_cmd' returns TRUE when 'args_cmd' valid", {
    args_cmd <- list("file1", "file2", n_iter = 3)
    args_dots  <- list(f1 = "f1", f2 = "f2", n_iter = 2)
    expect_true(check_args_cmd(args_cmd = args_cmd,
                               args_dots = args_dots))
    expect_true(check_args_cmd(args_cmd = args_cmd,
                               args_dots = rev(args_dots)))
})

test_that("'check_args_cmd' returns TRUE when 'args_cmd' empty", {
    args_cmd <- list()
    args_dots  <- list()
    expect_true(check_args_cmd(args_cmd = args_cmd,
                               args_dots = args_dots))
})

test_that("'check_args_cmd' throws expected error when named passed at command line not found in dots", {
    args_cmd <- list("file1", wrong = 3)
    args_dots  <- list(f1 = "f1", n_iter = 10)
    expect_error(check_args_cmd(args_cmd = args_cmd,
                                args_dots = args_dots),
                 paste("argument named \"wrong\" passed at command line",
                       "but no argument named \"wrong\" specified in call to 'file_args'"))                 
})

test_that("'check_args_cmd' throws expected error lengths of 'args_cmd' 'args_dots' differ", {
    args_cmd <- list("file1", "file2", n_iter = 3)
    args_dots  <- list(f1 = "f1", n_iter = 10)
    expect_error(check_args_cmd(args_cmd = args_cmd,
                                args_dots = args_dots),
                 paste("number of arguments passed at command line \\[3\\] not equal to",
                       "number of arguments specified in call to 'file_args' \\[2\\]"))
})


## 'check_args_dots' ----------------------------------------------------------

test_that("'check_args_dots' returns TRUE when 'args_dots' valid", {
    expect_true(check_args_dots(args_dots = list(a = 1, b = 2)))
})

test_that("'check_args_dots' throws errors when names are invalid", {
    ## do not test full error messages, since these are
    ## partly generated by checkmate::check_names
    expect_error(check_args_dots(args_dots = list(a = 1, a = 2)),
                 "names in call to 'file_args' invalid :")
})

test_that("'check_args_dots' throws errors when values are invalid", {
    expect_error(check_args_dots(args_dots = list(a = raw(), b = 2)),
                 "value in call to 'file_args' invalid : 'a' has class \"raw\"")
    expect_error(check_args_dots(args_dots = list(a = NULL, b = 2)),
                 "value in call to 'file_args' invalid : 'a' has class \"NULL\"")
})


## 'coerce_to_dots_class' -----------------------------------------------------

test_that("'coerce_to_dots_class' works with valid inputs", {
    args_cmd <- list(a = "TRUE", b = "1", c = "1", d = "1")
    args_dots <- list(a = NA, b = 1L, c = 1, d = "1")
    ans_obtained <- coerce_to_dots_class(args_cmd = args_cmd,
                                         args_dots = args_dots)
    ans_expected <- list(a = TRUE, b = 1L, c = 1, d = "1")
    expect_identical(ans_obtained, ans_expected)
})

test_that("'coerce_to_dots_class' throws correct error when cannot coerce", {
    args_cmd <- list(a = "TRUE", b = "1", c = "a", d = "1")
    args_dots <- list(a = NA, b = 1L, c = 1, d = "1")
    expect_error(coerce_to_dots_class(args_cmd = args_cmd,
                                      args_dots = args_dots),
                 paste("value for 'c' in call to 'file_args' has class \"numeric\",",
                       "but value for 'c' passed at command line \\[\"a\"\\]",
                       "cannot be coerced to class \"numeric\""))
})


## 'get_args_cmd' -------------------------------------------------------------

test_that("'get_args_cmd' works with valid inputs", {
    dir_curr <- getwd()
    dir_tmp <- tempfile()
    if (file.exists(dir_tmp))
        unlink(dir_tmp, recursive = TRUE)
    dir.create(dir_tmp)
    setwd(dir_tmp)
    writeLines(c("args <- argfun:::get_args_cmd()",
                 "saveRDS(args, file = 'args.rds')"),
               con = "script.R")
    cmd <- sprintf("%s/bin/Rscript script.R unnamed1 -n=1 unnamed2 --named=hello", R.home())
    system(cmd)
    args <- readRDS("args.rds")
    expect_identical(args, list("unnamed1", n = "1", "unnamed2", named = "hello"))
    setwd(dir_curr)
    unlink(dir_tmp, recursive = TRUE)
})

test_that("'get_args_cmd' works when no arguments passed", {
    dir_curr <- getwd()
    dir_tmp <- tempfile()
    if (file.exists(dir_tmp))
        unlink(dir_tmp, recursive = TRUE)
    dir.create(dir_tmp)
    setwd(dir_tmp)
    writeLines(c("args <- argfun:::get_args_cmd()",
                 "saveRDS(args, file = 'args.rds')"),
               con = "script.R")
    cmd <- sprintf("%s/bin/Rscript script.R", R.home())
    system(cmd)
    args <- readRDS("args.rds")
    expect_identical(args, list())
    setwd(dir_curr)
    unlink(dir_tmp, recursive = TRUE)
})


## 'is_p_objname' -------------------------------------------------------------

test_that("'is_p_objname' returns TRUE when 'x' starts a p suffix", {
    expect_true(is_p_objname("p_obj"))
    expect_true(is_p_objname("p.obj"))
    expect_true(is_p_objname("pObj"))
})

test_that("'is_p_objname' returns FALSE when 'x' does not start with a p suffix", {
    expect_false(is_p_objname(1L))
    expect_false(is_p_objname("P_obj"))
    expect_false(is_p_objname("pp.obj"))
    expect_false(is_p_objname("pobj"))
})


## 'is_rds_filename' ----------------------------------------------------------

test_that("'is_rds_filename' returns TRUE when 'x' is an RDS filename", {
    expect_true(is_rds_filename("myfile.rds"))
    expect_true(is_rds_filename("/dir1/dir2/myfile.rds"))
    expect_true(is_rds_filename("myfile.RDS"))
    expect_true(is_rds_filename(".rds"))
})

test_that("'is_rds_filename' returns FALSE when 'x' is not an RDS filename", {
    expect_false(is_rds_filename(1L))
    expect_false(is_rds_filename("myfile.rda"))
    expect_false(is_rds_filename("/dir1/dir2/myfile.xlsx"))
    expect_false(is_rds_filename("myfile.R"))
    expect_false(is_rds_filename("rds"))
})


## 'replace_rds_with_obj' -----------------------------------------------------

test_that("'replace_rds_with_obj' works with valid inputs", {
    dir_curr <- getwd()
    dir_tmp <- tempfile()
    if (file.exists(dir_tmp))
        unlink(dir_tmp, recursive = TRUE)
    dir.create(dir_tmp)
    setwd(dir_tmp)
    saveRDS(1:100, file = "fname.rds")
    args <- list(a = "fname.xlsx", b = "fname.rds", c = 1)
    ans_obtained <- replace_rds_with_obj(args)
    setwd(dir_curr)
    unlink(dir_tmp, recursive = TRUE)
    ans_expected <- list(a = "fname.xlsx", b = 1:100, c = 1)
    expect_identical(ans_obtained, ans_expected)
})

test_that("'replace_rds_with_obj' ignores names with p suffix", {
    args <- list(p_a = "fname.rds", p.b = "fname.rds", pC = "fname.rds")
    expect_identical(replace_rds_with_obj(args),
                     args)
})

test_that("'replace_rds_with_obj' works with no rds files", {
    args <- list(a = "fname.xlsx", b = "fname.csv", c = 1)
    expect_identical(replace_rds_with_obj(args),
                     args)
})

test_that("'replace_rds_with_obj' throws expected error", {
    dir_curr <- getwd()
    dir_tmp <- tempfile()
    if (file.exists(dir_tmp))
        unlink(dir_tmp, recursive = TRUE)
    dir.create(dir_tmp)
    setwd(dir_tmp)
    args <- list(a = "fname.xlsx", b = "fname.rds", c = 1)
    expect_error(replace_rds_with_obj(args),
                 "problem with function 'file_args' : attempt to call 'readRDS' with argument \"fname\\.rds\" failed :")
    setwd(dir_curr)
    unlink(dir_tmp, recursive = TRUE)
})





