
## 'assign_args' --------------------------------------------------------------

test_that("'assign_args' creates correct objects in the parent frame", {
    args <- list(xx = 1, yy = "hello", zz = TRUE)
    assign_args(args)
    expect_identical(xx, 1)
    expect_identical(yy, "hello")
    expect_identical(zz, TRUE)
    rm(xx, yy, zz)
})
    

## 'check_args_dots' ----------------------------------------------------------

test_that("'check_args_dots' returns TRUE when 'args_dots' valid", {
    expect_true(check_args_dots(args_dots = list(a = 1, b = 2),
                                 fun_name = "assign_named"))
})

test_that("'check_args_dots' throws errors when names are invalid", {
    ## do not test full error messages, since these are
    ## partly generated by checkmate::check_names
    expect_error(check_args_dots(args_dots = list(a = 1, a = 2),
                                 fun_name = "assign_named"),
                 "problem with names in '...' argument to 'assign_named' :")
    expect_error(check_args_dots(args_dots = list(a = 1, 2),
                                 fun_name = "assign_named"),
                 "problem with names in '...' argument to 'assign_named' :")
    expect_error(check_args_dots(args_dots = list(a = 1, "a-2" = 2),
                                 fun_name = "assign_named"),
                 "problem with names in '...' argument to 'assign_named' :")
})

test_that("'check_args_dots' throws errors when values are invalid", {
    expect_error(check_args_dots(args_dots = list(a = raw(), b = 2),
                                 fun_name = "assign_named"),
                 "problem with values in '...' argument to 'assign_named' : value for 'a' has class \"raw\"")
    expect_error(check_args_dots(args_dots = list(a = NULL, b = 2),
                                 fun_name = "assign_named"),
                 "problem with values in '...' argument to 'assign_named' : value for 'a' has class \"NULL\"")
})


## 'coerce_to_template' -------------------------------------------------------

test_that("'coerce_to_template' works with valid inputs", {
    ans_obtained <- coerce_to_template(vals = list("TRUE", "1", "1", "1"),
                                       names = c("a", "b", "c", "d"),
                                       templates = list(NA, 1L, 1, "1"),
                                       fun_name = "assign_unnamed")
    ans_expected <- list(TRUE, 1L, 1, "1")
    expect_identical(ans_obtained, ans_expected)
})

test_that("'coerce_to_template' throws correct error when cannot coerce", {
    expect_error(coerce_to_template(vals = list("TRUE", "1", "a", "1"),
                                    names = c("a", "b", "c", "d"),
                                    templates = list(NA, 1L, 1, "1"),
                                    fun_name = "assign_unnamed"),
                 paste("function 'assign_unnamed' unable to create object 'c' :",
                       "value \"a\" passed at command line cannot be coerced",
                       "to class \"numeric\""))
})


## 'get_args_cmd_named' -------------------------------------------------------

test_that("'get_args_cmd_named' picks out valid named arguments", {
    dir_curr <- getwd()
    dir_tmp <- tempfile()
    if (file.exists(dir_tmp))
        unlink(dir_tmp, recursive = TRUE)
    dir.create(dir_tmp)
    setwd(dir_tmp)
    writeLines(c("args <- argfun:::get_args_cmd_named()",
                 "saveRDS(args, file = 'args.rds')"),
               con = "script.R")
    cmd <- sprintf("%s/bin/Rscript script.R unnamed -n=1 --named=hello", R.home())
    system(cmd)
    args <- readRDS("args.rds")
    expect_identical(args, list(n = "1", named = "hello"))
    setwd(dir_curr)
    unlink(dir_tmp, recursive = TRUE)
})


## 'get_args_cmd_unnamed' -------------------------------------------------------

test_that("'get_args_cmd_unnamed' picks out valid unnamed arguments", {
    dir_curr <- getwd()
    dir_tmp <- tempfile()
    if (file.exists(dir_tmp))
        unlink(dir_tmp, recursive = TRUE)
    dir.create(dir_tmp)
    setwd(dir_tmp)
    writeLines(c("args <- argfun:::get_args_cmd_unnamed()",
                 "saveRDS(args, file = 'args.rds')"),
               con = "script.R")
    cmd <- sprintf("%s/bin/Rscript script.R unnamed1 -n=1 --named=hello unnamed2",
                   R.home())
    system(cmd)
    args <- readRDS("args.rds")
    expect_identical(args, list("unnamed1", "unnamed2"))
    setwd(dir_curr)
    unlink(dir_tmp, recursive = TRUE)
})


## 'is_named_arg' -------------------------------------------------------------

test_that("'is_named_arg' works with short names", {
    expect_true(is_named_arg("-a=1"))
    expect_true(is_named_arg("-a=hello"))
    expect_true(is_named_arg("-a=hello world"))
    expect_false(is_named_arg("a=1"))
    expect_false(is_named_arg("-=1"))
    expect_false(is_named_arg("-aa=1"))
    expect_false(is_named_arg("-a =1"))
    expect_false(is_named_arg("-a = 1"))
    expect_false(is_named_arg("-a =1"))
    expect_false(is_named_arg("-a:1"))
    expect_false(is_named_arg("-a 1"))
})

test_that("'is_named_arg' works with long names", {
    expect_true(is_named_arg("--aa=1"))
    expect_true(is_named_arg("--aa=hello"))
    expect_true(is_named_arg("--aa=hello world"))
    expect_false(is_named_arg("aa=1"))
    expect_false(is_named_arg("--=1"))
    expect_false(is_named_arg("--a =1"))
    expect_false(is_named_arg("-aa = 1"))
    expect_false(is_named_arg("--aa =1"))
    expect_false(is_named_arg("--a 1"))
})

test_that("'is_named_arg' works with short and long names", {
    expect_identical(is_named_arg(c("--aa=1", "-a=2")),
                     c(TRUE, TRUE))
})


## 'make_args_comb_named' -----------------------------------------------------

test_that("'make_args_comb_named' works with valid inputs", {
    ans_obtained <- make_args_comb_named(args_dots = list(a = NA,
                                                          b = 1L,
                                                          c = 1,
                                                          d = "1"),
                                         args_cmd = list(a = "TRUE",
                                                         b = "1",
                                                         c = "1",
                                                         d = "1"))
    ans_expected <- list(a = TRUE, b = 1L, c = 1, d = "1")
    expect_identical(ans_obtained, ans_expected)
    ans_obtained <- make_args_comb_named(args_dots = list(a = NA,
                                                          b = 1L,
                                                          c = 1,
                                                          d = "1"),
                                         args_cmd = list(c = "1",
                                                         b = "1",
                                                         d = "1",
                                                         a = "TRUE"))
    ans_expected <- list(a = TRUE, b = 1L, c = 1, d = "1")
    expect_identical(ans_obtained, ans_expected)
})

test_that("'make_args_comb_named' throws correct error when different names", {
    expect_error(make_args_comb_named(args_dots = list(a = NA, b = 1L, c = 1, d = "1"),
                                      args_cmd = list(a = "TRUE", d = "1")),
                 paste("problem with function 'assign_named' :",
                       "have argument named 'b' supplied in '...' but do not have",
                       "argument named 'b' passed at command line"))
    expect_error(make_args_comb_named(args_dots = list(b = 1L, a = NA),
                                      args_cmd = list(a = "TRUE", b = "1", c = "1")),
                 paste("problem with function 'assign_named' :",
                       "have argument named 'c' passed at command line",
                       "but do not have argument named 'c' supplied in '...'"))
})


## 'make_args_comb_unnamed' ---------------------------------------------------

test_that("'make_args_comb_unnamed' works with valid inputs", {
    ans_obtained <- make_args_comb_unnamed(args_dots = list(a = NA, b = 1L, c = 1, d = "1"),
                                           args_cmd = list("TRUE", "1", "1", "1"))
    ans_expected <- list(a = TRUE, b = 1L, c = 1, d = "1")
    expect_identical(ans_obtained, ans_expected)
})

test_that("'make_args_comb_unnamed' throws correct error when different number of arguments", {
    expect_error(make_args_comb_unnamed(args_dots = list(a = NA, b = 1L, c = 1, d = "1"),
                                        args_cmd = list("TRUE")),
                 paste("problem with function 'assign_unnamed' :",
                       "4 name-value pairs supplied in '...' and",
                       "1 unnamed argument passed at command line"))
    expect_error(make_args_comb_unnamed(args_dots = list(a = NA),
                                        args_cmd = list("TRUE", "1", "1", "1")),
                 paste("problem with function 'assign_unnamed' :",
                       "1 name-value pair supplied in '...' and",
                       "4 unnamed arguments passed at command line"))
})
