
## 'check_args_dots' ----------------------------------------------------------

test_that("'check_args_dots' returns TRUE when 'args_dots' valid", {
    expect_true(check_args_dots(args_dots = list(a = 1, b = 2),
                                 fun_name = "assign_named"))
})

test_that("'check_args_dots' throws errors when names are invalid", {
    ## do not test full error messages, since these are
    ## partly generated by checkmate::check_names
    expect_error(check_args_dots(args_dots = list(a = 1, a = 2),
                                 fun_name = "assign_named"),
                 "problem with names in '...' argument to 'assign_named' :")
    expect_error(check_args_dots(args_dots = list(a = 1, 2),
                                 fun_name = "assign_named"),
                 "problem with names in '...' argument to 'assign_named' :")
    expect_error(check_args_dots(args_dots = list(a = 1, "a-2" = 2),
                                 fun_name = "assign_named"),
                 "problem with names in '...' argument to 'assign_named' :")
})

test_that("'check_args_dots' throws errors when values are invalid", {
    expect_error(check_args_dots(args_dots = list(a = raw(), b = 2),
                                 fun_name = "assign_named"),
                 "problem with values in '...' argument to 'assign_named' : value for 'a' has class \"raw\"")
    expect_error(check_args_dots(args_dots = list(a = NULL, b = 2),
                                 fun_name = "assign_named"),
                 "problem with values in '...' argument to 'assign_named' : value for 'a' has class \"NULL\"")
})


## 'get_args_cmd_named' -------------------------------------------------------

test_that("'get_args_cmd_named' picks out valid named arguments", {
    dir_curr <- getwd()
    dir_tmp <- tempfile()
    if (file.exists(dir_tmp))
        unlink(dir_tmp, recursive = TRUE)
    dir.create(dir_tmp)
    setwd(dir_tmp)
    writeLines(c("args <- argfun:::get_args_cmd_named()",
                 "saveRDS(args, file = 'args.rds')"),
               con = "script.R")
    cmd <- sprintf("%s/bin/Rscript script.R unnamed -n=1 --named=hello", R.home())
    system(cmd)
    args <- readRDS("args.rds")
    expect_identical(args, list(n = "1", named = "hello"))
    setwd(dir_curr)
    unlink(dir_tmp, recursive = TRUE)
})


## 'get_args_cmd_unnamed' -------------------------------------------------------

test_that("'get_args_cmd_unnamed' picks out valid unnamed arguments", {
    dir_curr <- getwd()
    dir_tmp <- tempfile()
    if (file.exists(dir_tmp))
        unlink(dir_tmp, recursive = TRUE)
    dir.create(dir_tmp)
    setwd(dir_tmp)
    writeLines(c("args <- argfun:::get_args_cmd_unnamed()",
                 "saveRDS(args, file = 'args.rds')"),
               con = "script.R")
    cmd <- sprintf("%s/bin/Rscript script.R unnamed1 -n=1 --named=hello unnamed2",
                   R.home())
    system(cmd)
    args <- readRDS("args.rds")
    expect_identical(args, list("unnamed1", "unnamed2"))
    setwd(dir_curr)
    unlink(dir_tmp, recursive = TRUE)
})


## 'is_named_arg' -------------------------------------------------------------

test_that("'is_named_arg' works with short names", {
    expect_true(is_named_arg("-a=1"))
    expect_true(is_named_arg("-a=hello"))
    expect_true(is_named_arg("-a=hello world"))
    expect_false(is_named_arg("a=1"))
    expect_false(is_named_arg("-=1"))
    expect_false(is_named_arg("-aa=1"))
    expect_false(is_named_arg("-a =1"))
    expect_false(is_named_arg("-a = 1"))
    expect_false(is_named_arg("-a =1"))
    expect_false(is_named_arg("-a:1"))
    expect_false(is_named_arg("-a 1"))
})

test_that("'is_named_arg' works with long names", {
    expect_true(is_named_arg("--aa=1"))
    expect_true(is_named_arg("--aa=hello"))
    expect_true(is_named_arg("--aa=hello world"))
    expect_false(is_named_arg("aa=1"))
    expect_false(is_named_arg("--=1"))
    expect_false(is_named_arg("--a =1"))
    expect_false(is_named_arg("-aa = 1"))
    expect_false(is_named_arg("--aa =1"))
    expect_false(is_named_arg("--a 1"))
})

test_that("'is_named_arg' works with short and long names", {
    expect_identical(is_named_arg(c("--aa=1", "-a=2")),
                     c(TRUE, TRUE))
})


    

