---
title: "argfun"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(argfun)
```
```{r}
tmpdir <- tempdir()
if (!file.exists(tmpdir))
  dir.create(tmpdir)

## create a file called "product.R"
txt <- c(
  "library(argfun)",
  "target <- target()",
  "variant <- opt_target(target)",
  "multiplier <- if (variant == 'high') 10 else 5",
  "product <- multiplier * 7",
  "saveRDS(product, file = target)"
)
writeLines(txt, con = file.path(tmpdir, "product.R"))

## check that the file was created correctly
dir(tmpdir)
readLines(file.path(tmpdir, "product.R"))

## run the file from the command line twice,
## with two different targets
cmd_high <- sprintf("$(R_HOME)/bin/Rscript %s %s",
                    file.path(tmpdir, "product.R"),
                    file.path(tmpdir, "product-high.rds"))
cmd_low <- sprintf("$(R_HOME)/bin/Rscript %s %s",
                   file.path(tmpdir, "product.R"),
                   file.path(tmpdir, "product-low.rds"))

system(cmd_high)
system(cmd_low)

## check that the new files were created correctly
dir(tmpdir)

## read the contents of the new files
readRDS(file.path(tmpdir, "product-high.rds"))
readRDS(file.path(tmpdir, "product-low.rds"))

## tidy up
unlink(tmpdir, recursive = TRUE)
```